In [41]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr1)

print()
arr2=np.array([1,2,3,4,5,6,7])
print(arr2[1:4])
print(arr2[-4:-1])
print(arr2[-1])
print(arr2[1:5:2])
print(arr2[::3])
print()

arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3[1,:])
print(arr3[0:2,3])
print(arr3[0:1,2:5])

print()
arr4=np.array([])
x=np.where(arr4==4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[2 3 4]
[4 5 6]
7
[2 4]
[1 4 7]

[ 6  7  8  9 10]
[4 9]
[[3 4 5]]


In [55]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
suma=x+y
print(f"La suma es {suma}")
resta=x-y
print(f"La resta es {resta}")
mult=x*y
print(f"La multiplicacion es {mult}")
div=x/y
print(f"La division es {div}")

print(f"Numero pi = {np.pi}")
angulos=np.array([0,np.pi/2,np.pi])
coseno=np.cos(angulos)
seno=np.sin(angulos)
print("Loc senos de los angulos son")
print(f"{seno}")
print("Loc cosenos de los angulos son")
print(f"{coseno}")

La suma es [5 7 9]
La resta es [-3 -3 -3]
La multiplicacion es [ 4 10 18]
La division es [0.25 0.4  0.5 ]
Numero pi = 3.141592653589793
Loc senos de los angulos son
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
Loc cosenos de los angulos son
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [63]:
import numpy as np
x=np.array(list(range(1,9)))
print(x)
matriz=x.reshape(2,4)
print(matriz)
matriz=matriz.reshape(4,2)
print(matriz)
x=np.linspace(0,1,4)
print(x)
print(np.random.uniform(0,1,6))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[0.         0.33333333 0.66666667 1.        ]
[0.2659741  0.5440036  0.85289332 0.39079306 0.40320895 0.33430922]


In [104]:
import numpy as np
arr=np.array(range(1,11))
print(arr)
n=input("Escribe un numero del 1 al 10 ")
n=int(n)

i=0
while(i<=4):
  r=np.random.randint(1,11)
  if r==n:
    print(f"Este es tu numero {n}")
    break
  else:
    print(f"Numero encontrado {r}")
  i+=1

[ 1  2  3  4  5  6  7  8  9 10]
Escribe un numero del 1 al 10 1
Numero encontrado 6
Numero encontrado 4
Numero encontrado 3
Este es tu numero 1
