In [ ]:
import numpy as np

arr=np.array([0])

arr1=np.array([1,2,3,4,5,6])
print(arr1)

print(arr1[2])

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1][1])

print()
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3[0][1][2])

print()
print(arr.ndim, arr.shape)
print(arr1.ndim, arr1.shape)
print(arr2.ndim, arr2.shape)
print(arr3.ndim, arr3.shape)

[1 2 3 4 5 6]
3
[[1 2 3]
 [4 5 6]]
5

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
6

1 (1,)
1 (6,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
import numpy as np
A=[[1,2,3],[4,5,6],[7,8,9]]
B=np.array(([1,2,3],[4,5,6],[7,8,9]))
suma=0
suma2=0

for i in range(len(A)):
  for j in range(len(A)):
    suma+=int(A[i][j])

for i in range(len(B)):
  for j in range(len(B)):
    suma2+=int(B[i][j])

print(A[0][1])
print(B[2][2])
print()
print("Suma de matriz con listas: " + str(suma))
print("Suma de matiz con arreglos: " + str(suma2))

a=[[1,2],[3,4]]
b=[[5,6],[7,8]]

c=np.array(([1,2],[3,4]))
d=np.array(([5,6],[7,8]))
e=np.array(([1,1,1],[1,1,1],[1,1,1]))
f=np.array(([1,1,1],[1,1,1],[1,1,1]))
suma3=0
suma4=0
suma5=0

for i in range(len(a[0])):
  suma3+=a[0][i]*b[0][i]
print("Producto interno renglones: " + str(suma3))

for i in range(len(c[0])):
  suma4+=c[i][0]*d[i][0]
print("Producto interno columnas: " + str(suma4))

for i in range(len(e)):
  for j in range(len(e)):
    suma5+=e[i][j]*f[i][j]

print("Suma producto interno: " + str(suma5))

2
9

Suma de matriz con listas: 45
Suma de matiz con arreglos: 45
Producto interno renglones: 17
Producto interno columnas: 26
Suma producto interno: 9
